#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=/Users/ZeJr/Library/Caches/pypoetry/virtualenvs/maistodos-api-PIT-NR5o-py3.10/bin/python
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated

# if [ -x "$INSTALL_PYTHON" ]; then
#     cz commit
#     cd maistodos && exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}" --hook-dir .
# elif command -v pre-commit > /dev/null; then
#     exec pre-commit "${ARGS[@]}"
# else
#     echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
#     exit 1
# fi
